name: get fcc pull requests

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 2 * * *'
  # Allows you to manually trigger the action anytime from the GitHub Actions tab
  workflow_dispatch:
      
jobs:
  update_prs:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v7
        with: 
          ref: ${{ github.head_ref }}
          persist-credentials: true
      - name: rungh
        run: |
          gh api graphql -f query='query { organization(login: "key4hep") { repositories { nodes { name pullRequests(states: OPEN) { nodes { number title author { login } createdAt updatedAt mergeable url } } } } } }'  > key4hep.json
          gh api graphql -f query='query { organization(login: "hep-fcc") { repositories { nodes { name pullRequests(states: OPEN) { nodes { number title author { login } createdAt updatedAt mergeable url } } } } } }'  > hep-fcc.json
        env:
          GH_TOKEN: ${{ secrets.FCC_GH_TOKEN }}
      - name: translategh
        run: ls -l; python3 reformulate_json.py key4hep.json hep-fcc.json; mv data.json sample.json; rm key4hep.json hep-fcc.json
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v7
    
        

