name: get fcc pull requests
on:
  issues:
    types:
      - opened
      - reopened
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: rungh
        run: gh api graphql -f query='query { organization(login: "key4hep") {repositories(first: 100) { nodes { name pullRequests(first: 30, states: OPEN) { nodes { number title author { login } createdAt updatedAt mergeable url } } } } } }' > gh.json
      - name: translategh
        run: python3 reformulate_json.py

     
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          ISSUE: ${{ github.event.issue.html_url }}
